# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11.2
language: objective-c
xcode_workspace: Example/DimensionsPickerView.xcworkspace
xcode_scheme: DimensionsPickerView-Example
xcode_sdk: platform=iOS Simulator,OS=10.1,name=iPhone 8
